"""Pierwsza migracja zoo

Revision ID: aa68cb045df9
Revises: 
Create Date: 2025-12-01 19:00:38.033981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa68cb045df9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zwierzeta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gatunek', sa.String(length=100), nullable=True),
    sa.Column('wiek', sa.Integer(), nullable=True),
    sa.Column('czy_niebezpieczne', sa.Boolean(), nullable=True),
    sa.Column('ilosc', sa.Integer(), nullable=True),
    sa.Column('klimat', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zwierzeta_gatunek'), 'zwierzeta', ['gatunek'], unique=False)
    op.create_index(op.f('ix_zwierzeta_id'), 'zwierzeta', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zwierzeta_id'), table_name='zwierzeta')
    op.drop_index(op.f('ix_zwierzeta_gatunek'), table_name='zwierzeta')
    op.drop_table('zwierzeta')
    # ### end Alembic commands ###
